version: '3.8'

services:
  kspdb-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kspdb_fault_localization
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always
